== Aspectos básicos de Git

=== Instalación

==== Instalando en Linux

Si quieres instalar Git en Linux a través de un instalador binario, en
general puedes hacerlo a través de la herramienta básica de gestión de
paquetes que trae tu distribución. Si estás en un derivado de Red Hat,
puedes usar `dnf`:

....
$ dnf install git-all
....

O si estás en una distribución basada en Debian como Ubuntu, prueba con
`apt`:

....
$ apt install git-all
....

==== Instalando en Windows

Accede a https://git-scm.com/download/win y descarga la versión más
apropiada.

==== Instalando en MacOS

En MacOS se recomienda tener instalada la herramienta
https://brew.sh/[homebrew]. Después, ejecutar:

....
$ brew install git
....

=== Configuración

==== Tu identidad

Lo primero que deberías hacer cuando instalas Git es establecer tu
nombre de usuario y dirección de correo electrónico. Esto es importante
porque las confirmaciones de cambios (commits) en Git usan esta
información, y es introducida de manera inmutable en los commits que
envías:

....
$ git config --global user.name "John Doe"
$ git config --global user.email johndoe@example.com
....

También se recomienda configurar el siguiente parámetro:

....
$ git config --global push.default simple
....

==== Bash Completion

_Bash completion_ es una utilidad que permite a bash completar órdenes y
parámetros. Por defecto suele venir desactivada en Ubuntu y es necesario
modificar el archivo `$HOME/.bashrc` para poder activarla. Simplemente
hay que descomentar las líneas que lo activan,
